#!/bin/bash

VERSION="1.5.2"

# Settings

USE_HEAD=y
USE_PLURAL=n

SHOW_KERNEL=n
SHOW_VERSION=y

STRIP_PRETAGS=y
STRIP_SUBVERSIONS=y

# Storing our package list.

dpkg -l >> /tmp/__dpkgl_tmp

# List of distro release version locations.

DISTROS=(
	# Debian

	'debian_version,Debian'
	'debian_release,Debian'

	# Ubuntu

	'lsb-release,Ubuntu'
)

# Array PROCESS | PACKAGE,[n] | DISPLAY

ENVIRONMENTS=(
	'gnome-*|gnome-core,gnome-desktop-environment|Gnome'
	'plasma-*|kde-core,kde-desktop|KDE'
	'xfce4|xfce4|XFCE'
	'lxde-*|lxde,lxde-core|LXDE'
	'openbox|openbox|OpenBox'
	'fluxbox|fluxbox|FluxBox'
	'enlightenment|e17|Enlightenment'
	'icewm|icewm,icewm-lite,icewm-experimental|IceWM'

	'metacity|metacity|Metacity'
	'kwin|kwin,kde-window-manager|KWin'
	'compiz|compiz,compiz-gnome,compiz-kde|Compiz'
	'emerald|emerald|Emerald'
	'mutter|mutter|Mutter'
	'xfwm|xfwm4|XFWM'
	'awesome|awesome|Awesome'
)

BROWSERS=(
	'chrome|google-chrome-stable,google-chrome-unstable,google-chrome-beta|Google Chrome'
	'chromium|chromium-browser|Chromium'
	'firefox|firefox,iceweasel,firefox-3.6,firefox-3.5|Firefox'
	'opera|opera|Opera'
	'konqueror|konqueror|Konqueror'
	'epiphany-browser|epiphany-browser|Epiphany'
	'midori|midori|Midori'
)

DOCKS=(
	'docky|docky|Docky'
	'avant-window-navigator|avant-window-navigator|AWN'
	'cairo|cairo-dock,cairo-dock-core,cairo-dock-dev|Cairo-Dock'
	'kibadock|kiba-dock|Kiba-Dock'
)

PLAYERS=(
	'mplayer|mplayer,mplayer-gui,mplayer-gnome|MPlayer'
	'totem|totem|Totem'
	'kaffeine|kaffeine|Kaffeine'
	'vlc|vlc|VLC'

	'rhythmbox|rhythmbox|Rhythmbox'
	'amarok|amarok|Amarok'
	'banshee|banshee|Banshee'
	'exaile|exaile|Exaile'
)

MESSENGERS=(
	'pidgin|pidgin|Pidgin'
	'empathy|empathy|Empathy'
	'emesene|emesene|Emesene'
	'amsn|amsn|AMSN'
	'kopete|kopete|Kopete'

	'xchat|xchat|XChat'
	'quassel|quassel,quassel-client|Quassel'
	'irssi|irssi|Irssi'
	'kvirc|kvirc|Kvirc'
)

SOCIALSHIT=(
	'pino|pino|Pino'
	'gwibber|gwibber|Gwibber'
	'twitux|twitux|Twitux'
)

function process_search {
	P=`ps aux | grep -v 'grep' | grep -m1 $1`

	if [ -z "$P" ]; then
		return 0
	else
		return 1
	fi
}

function process_name {
	echo "$1" | cut -d '|' -f3
}

function process_version {
	L=`echo $1 | cut -d '|' -f2`
	S=`echo $L | awk -F ',' '{print NF}'`

	for (( K=0; K < $S; K++ ))
	do

		PACKAGE=`echo $L | cut -d ',' -f$((K + 1))`
		PACKAGE_VERSION=`cat /tmp/__dpkgl_tmp | grep -m1 "^ii  $PACKAGE" | awk '{print $3}'`

		if [ -n "$PACKAGE_VERSION" ]; then

			if [ "$STRIP_PRETAGS" == "y" ]; then
				PACKAGE_VERSION=`echo $PACKAGE_VERSION | sed 's/[0-9]://'`
			fi

			if [ "$STRIP_SUBVERSIONS" == "y" ]; then
				PACKAGE_VERSION=`echo $PACKAGE_VERSION | cut -d '-' -f1 | cut -d '+' -f1`
			fi

			echo $PACKAGE_VERSION

			K=$S

		fi

	done
}

function show_help {
	echo "Usage: tell [OPTIONS]"
	echo
	echo "  -a			show (known) apps in use"
	echo
	echo "  -a			show environment specs"
	echo "  -b			show open browser(s)"
	echo "  -d			show open dock(s)"
	echo "  -m			show open messenger(s)"
	echo "  -s			show open social apps"
	echo "  -p			show open audio\video player(s)"
	echo
	echo "  -h			display this help"
}

function show_distro {
	unset V

	for each in ${DISTROS[*]}; do
		D=`echo $each | cut -d ',' -f1`

		[ "$V" ] && break || [ -r /etc/$D ] && V=$(awk '{print $1}' /etc/$D)
	done

	O=`echo $each | cut -d ',' -f2`

	echo "  $O $V"

	if [ "$SHOW_KERNEL" == "y" ]; then
		echo "  `uname -n` @ `uname -r`"
	else
		echo "  $USER @ $HOSTNAME"
	fi
}

function show_task {
	unset OUT
	eval SIZE=\${#${1}[*]}

	for (( C=0; C < $SIZE; C++ ))
	do
		eval CURRENT=\${${1}[$C]}

		PROCESS=`echo $CURRENT | cut -d '|' -f1`

		process_search $PROCESS
		S=$?

		if [ "$S" == 1 ]; then

			if [ "$SHOW_VERSION" == "y" ]; then
				OUT="${OUT}   `process_name "$CURRENT"`|     `process_version "$CURRENT"`\n"
			else
				OUT="${OUT}   `process_name "$CURRENT"`\n"
			fi

		fi
	done

	if [ "$2" == "R" ]; then
		echo "$OUT"
	else
		echo -e "$OUT" | column -s '|' -t
	fi
}

function show_all {
	Y="${Y}`show_task ENVIRONMENTS R`|\n|`show_task BROWSERS R`|`show_task DOCKS R`|`show_task MESSENGERS R`|`show_task SOCIALSHIT R`|`show_task PLAYERS R`"

	show_distro
	echo
	echo -e "$Y" | column -s '|' -t
}


while getopts  "habdemps" OPT
do

	case $OPT in
		h)
			show_help

			exit 0
			;;
		a)
			echo

			if [ "$USE_HEAD" == "y" ]; then
				echo "	Apps"
				echo
			fi

			APPS="${APPS}   `show_task BROWSERS R`|   `show_task DOCKS R`|   `show_task MESSENGERS R`|   `show_task SOCIALSHIT R`|   `show_task PLAYERS R`"
			echo -e "$APPS" | column -s '|' -t

			echo
			;;
		b)
			echo

			if [ "$USE_HEAD" == "y" ]; then

				if [ "$USE_PLURAL" == "y" ]; then
					echo "	Browser(s)"
				else
					echo "	Browser"
				fi

				echo

			fi

			show_task BROWSERS
			echo
			;;
		d)
			echo

			if [ "$USE_HEAD" == "y" ]; then

				if [ "$USE_PLURAL" == "y" ]; then
					echo "	Dock(s)"
				else
					echo "	Dock"
				fi

				echo

			fi

			show_task DOCKS
			echo
			;;
		e)
			echo

			if [ "$USE_HEAD" == "y" ]; then
				echo "	Environment"
				echo
			fi

			show_task ENVIRONMENTS
			echo
			;;
		m)
			echo

			if [ "$USE_HEAD" == "y" ]; then

				if [ "$USE_PLURAL" == "y" ]; then
					echo "	Messenger(s)"
				else
					echo "	Messenger"
				fi

				echo

			fi

			show_task MESSENGERS
			echo
			;;
		p)
			echo

			if [ "$USE_HEAD" == "y" ]; then

				if [ "$USE_PLURAL" == "y" ]; then
					echo "	Player(s)"
				else
					echo "	Player"
				fi

				echo

			fi

			show_task PLAYERS
			echo
			;;
		s)
			echo

			if [ "$USE_HEAD" == "y" ]; then
				echo "	Social"
				echo
			fi

			show_task SOCIALSHIT
			echo
			;;
	esac

done

if [ "$OPTIND" -eq "1" ]; then
	echo
	show_all
	echo
fi

rm /tmp/__dpkgl_tmp

exit 0
